### PR TITLE
Update harbour-tooter-zh_CN.ts

### PR DESCRIPTION
**Pull request by dashinfantry**

### CODE REVIEW

**Comment by molan-git** [comment]
Thank you very much again for your translations. If you want I would like to mention you in the app.
I would need: 
                            name: "Your real name or nickname"
                            desc: qsTr("Chinese translation")
                            mastodon: "your mastodon account (optional)"
                            mail: "your e-mail (optional)"

Let me know! You can also send me an E-mail (which you find in the app).

**Comment by dashinfantry** [comment]
Name:Luchy Kon
Mastodon:@dashinfantry 
Email:dashinfantry@gmail.com  星期五, 31 一月 2020, 03:47下午 +08:00 发件人 molan-git  notifications@github.com :

**Comment by molan-git** [comment]
Fantastic, thanks. Could you also translate this string - this way I can include it in the translation file myself in the next update: 

qsTr("Chinese translation")

**Comment by dashinfantry** [comment]
qsTr("Chinese translation")
qsTr("汉语翻译") :) 星期五, 31 一月 2020, 04:21下午 +08:00 发件人 molan-git  notifications@github.com :

**Comment by molan-git** [comment]
Thanks, I will publish a small update soon.

**Pull request merged**
